[tools]
lefthook = "2.0.11"
cocogitto = "6.5.0"
act = "0.2.83"
golang = "1.25.5"
golangci-lint = "2.7.2"

[tasks.clean]
run = "rm -rf bin"

[tasks.setup]
run = "go mod download && lefthook install"

[tasks.format]
run = "golangci-lint run --fix --allow-parallel-runners"

[tasks.lint]
run = "golangci-lint run --allow-parallel-runners"

[tasks.test]
run = "go test ./..."

[tasks.check]
depends = ["format", "lint", "test"]

[tasks.pre-commit]
depends = ["format", "lint"]

[tasks.build]
env = { CGO_ENABLED = "0", GOOS = "linux", GOARCH = "amd64" }
run = 'go build -ldflags="-s -w" -trimpath -o bin/app cmd/app/main.go'

[tasks.run]
run = "go run ./cmd/app"

[tasks.start]
depends = ["build"]
run = "./bin/app"

[tasks.act]
run = 'act pull_request --secret-file .env -e .github/act/pull_request.json -j checks'
